src/matlab2tikz.m, src/private/m2tUpdater.m
(same as #499)
Practically rewrote the updater, since the FEX forwards the download request to Github latest master. 
Also, the folder structure is packed into an additional folder, the MATLAB Search Path 	`/matlab2tikz-matlab2tikz-76c2ac0` (see [FEX](http://uk.mathworks.com/matlabcentral/fileexchange/22022-matlab2tikz-matlab2tikz)). If we were to remove it from FEX, we could simplify things a bit.
=> Fix updater

src/matlab2tikz.m
Instead of `setdiff()` (used in `getRelevantAxes`) which reorders the axes handles, keep the previously queried order of the handles. The order of the handles is reversed later in `m2t` and with `setdiff()` it's basically nullified. 
Fixes the ordering problem in https://github.com/matlab2tikz/matlab2tikz/issues/6
=> Keep axes plotting order

src/matlab2tikz.m
Together with #509 fixes #6 since enforces color bg of axis when there are multiple axes and the current one is visible. Basically, complex plot with axes overlays, see `ACID(14)`, will mantain transparency while still plotting the children (lines). 
Also:
* renamed `axisIsVisible` to `isAxisVisible`
* in `getRelevantAxes` made double conversion of axes handles explicit
* store `relevantAxesHandles` in `m2t`, which is needed for the multiple axes check in `drawBackgroundOfAxes`
=> Axis background

src/matlab2tikz.m
Improves `ACID(91) - annotationTextUnits` and lets Matlab carry out the conversion from e.g. `characters` to `centimeters`. The bottom right box is finally close enough, compare against `ACID(90)`.
Refactored the function (also in preparation for 3D check on axis).
=> Fix getPositionOfText (improves annotation positioning)

src/matlab2tikz.m, test/suites/ACID.m
Fixes #259 and `ACID(50) - axesLocation` bug of missing box when flipping x/y axis to top/right.
=> Fix axesLocation missing box bug

src/matlab2tikz.m, test/suites/ACID.m
These fixes are mostly relevant for Octave and are preliminary to conclude #503 (so that I can post the bar plot rendering in Octave).
Fixes the short term part of #507 and handles scalar `cdata` when drawing patches (which are used to draw bar plots in Octave)
=> Octave fixes

src/matlab2tikz.m
Fixes #443 and #338, i.e. uses now axis units for bar width/shift. This implicitly deals with multiple barplots created with hold on (thus fixes #338).
Also, I am getting rid of `countBarplotSiblings()` and retrieving the  bar group directly when plotting grouped. Octave 's property is 'bargroup' and Matlab's hidden property is 'BarPeers', which exists in both R2014a and b.
`Shift` and `barId` are calculated locally from the bargroup. This avoids popping up some properties into the `m2t` container. 
Tested on R2014a,b and Octave. Gonna submit .pdfs next days.
=> Bar width in units, retrieve bar peers directly

src/matlab2tikz.m
This is not properly handled by octave 3.8.2 and produces the literal
output "$$2$", when the testsuite was executed.
The change does not affect the bahavior of MATLAB.
ACID(68) octave
ACID(68) R2014b
=> Do not escape dollar in replacement string (e.g., "\$$2\$")

src/matlab2tikz.m
* octave does not know the property 'pos'
* introduced by commit 41b415bab9da520e9c850f1b387987f36fc40a35
requires PR #520
fixes #515
=> fix ACID(69) for octave

src/matlab2tikz.m, test/suites/ACID.m
Code
```
plot(magic(3))
title('a>O');
```
would fail.
Testcase ACID(64) is slightly extended to cover that issue.
=> Fix math textgreater

src/matlab2tikz.m, test/suites/ACID.m
Fixes #525 by adding support for `histogram()`.
On the left side the transparency is lost possibly due to `cleanfigure()`
=> Histogram support

src/matlab2tikz.m
Improve backwards compatibility in Matlab up to 2008a (ACID compiles).
=> Use dummy in place of ~ in out

src/matlab2tikz.m, test/suites/ACID.m
Introducing annotations for HG2 with some work left to do (not in this PR).
Also, re-organized a bit the annotations tests inside ACID, to include all possible annotations.
TODO (will submit as feature request but listing here to keep in mind):
* write a `drawArrow()` to handle (both) arrow annotations. Handle all info info directly without using `handleAllChildren()` since in HG2 arrow annotations have no children (so no shortcut as used in R2014a). 
It would be good if `drawArrow()` was callable on a `matlab.graphics.shape.TextArrow` object to draw the arrow part.
* rewrite drawTextarrow. Handle all info info directly without using `handleAllChildren()` for same reason as above.
=> Annotations HG2

src/matlab2tikz.m
See https://github.com/matlab2tikz/matlab2tikz/pull/535 (closed by mistake)
Explicitly deal with HG2, HG1 and Octave idiosyncrasies
=> Matlab explicit use of handle()

src/cleanfigure.m, test/suites/ACID.m
Existing ACID(21) `pruneOutsideBox()` is fixed and ACID(7) `linesWithOutliers` keeps working:
Fixes issues #392 and #400.
**edit:** Thanks go to @akloeckner for providing the missing real fix (PR #547). I incorporated it here, since I added quite some comments and restructured the code a little bit.
=> Fix issues #392 and #400 caused by cleanfigure

src/matlab2tikz.m
This fixes #548.
There is a single occurrance where this patch isn't applied yet, since I'm unsure whether that case allows for external tables.
TODOs have been left at that location.
**The correctness has been tested against the framework in #485 (by cherry-picking on top of this and running the suite in R2014b).**
Only `ACID(83)` produces different output. I have diffed the output against the current HEAD of #485 and the difference is an improvement as you can see below (only the different part is shown):
before:
```latex
[row sep=crcr,]{%
```
after (this PR):
```latex
[row sep=crcr]{%
```
So, I think we are better off like this, but this is something we have to look out for after merging #485.
=> Only add "row sep=crcr" if not externalData

src/figure2dot.m, src/matlab2tikz.m, test/makeLatexReport.m, test/private/VersionControlIdentifier.m, test/private/execute_save_stage.m, test/private/loadHashTable.m, test/saveHashTable.m
Some `try-catch` constructions -- that rethrew the error AFTER `fclose(fid)` --
were also removed, since these were no longer needed.
This will close #508 when merged.
=> Use `onCleanup` to close all files

src/matlab2tikz.m
Fixes two bugs related to the handling of transparent images: 
1. alpha data needs to be flipped along with color data if axis direction is reversed
2. integer alpha data should not be clipped to [0,1]
Here is a small example to illustrate the problems:
```matlab
figure;
line([0.5,2.5],[0.5,2.5],'linewidth',2,'color','k');
line([0.5,2.5],[2.5,0.5],'linewidth',2,'color','k');
hold on
imagesc([0,1;2,3],'AlphaData',uint8([64,128;192,256]))
```
This is what the output should look like in Matlab:
This is what the tikz ouput looks like before the fix:
(rendering may vary depending on pdf reader)
and after:
=> Fix transparency

src/matlab2tikz.m, test/private/execute_save_stage.m, test/private/getEnvironment.m, test/suites/ACID.m, test/suites/private/getEnvironment.m, test/suites/private/isVersionBelow.m, test/suites/private/versionCompare.m, test/suites/testSurfshader.m
This fixes #563. Basically, I got fed up of passing `m2t` around to access the global variable `env`. From within `matlab2tikz`, I've replaced all instances that I could find.
On the way, I found a little bug that was not covered by any test case (since it only occurs in error situations). I fixed it anyway :smile_cat:
=> Refactor environment

src/matlab2tikz.m, test/suites/ACID.MATLAB.8.4.md5
This partially addresses #391 and the situation afterwards is going to be:
Function          |Complexity 
----------------------------|-----------
`drawPatch`         |    22     
`matlabTicks2pgfplotsTicks` |    19     
`drawScatterPlot`      |    18     
`shaderOptsSurfPatch`    |    14     
`getMarkerOptions`     |    13     
`findLegendInformation`   |    11     
**Total**          |    97     
Some TODOs in the code were also taken care of, since these overlapped with the changes I intended. More specifically: `[XYZ]Label`, `Label` and `Title` now share common code. This means for most labels that we now also support a bit more formatting options. These are not covered by ACID.
=> Simplify yet some more

src/matlab2tikz.m, test/suites/ACID.MATLAB.8.3.md5, test/suites/ACID.MATLAB.8.4.md5, test/suites/ACID.Octave.3.8.0.md5, test/suites/ACID.m
Consider `faceAlpha` and `edgeAlpha`
Do this, if a single patch is considered.
This fixes #593.
**Test code:**
```
contourf(peaks(5)); hold on;
h = fill([2 2 4 4], [2 3 3 2],'b');
set(h,'FaceColor', 'r');
set(h,'FaceAlpha', 0.2);
set(h,'EdgeColor', 'g');
set(h,'EdgeAlpha', 0.5);
set(h,'LineStyle', ':');
set(h,'LineWidth', 3);
set(h,'Marker', 'x');
set(h,'MarkerSize', 12);
```
**Output with patch:**
=> FIX #594 - FaceAlpha and EdgeAlpha

test/private/execute_hash_stage.m, test/private/testMatlab2tikz.m
see https://github.com/egeerardyn/matlab2tikz/commit/583251956adf3804577c27865dd90e15ee8043f8
I had the same problem, so went ahead and fixed this.
Personally I think that https://github.com/matlab2tikz/matlab2tikz/issues/575 is unrelated, but want to add the reference, in case this should be reviewed during the restructuring.
=> Reinitialize hashes as indicated in `getReferenceHash()`

src/matlab2tikz.m, test/suites/ACID.MATLAB.8.4.md5, test/suites/ACID.m
I've spent my Sunday refactoring some parts, mainly to address #391, but also some other things that have been bothering me for a while. Note that since everything should be a refactoring, no additional functionality has been included.
* I've added a `FIXME` tag in ee9a811 where we can change the Z-order of the axes/grids/... (I have been dragging that commit along for a bit too long now, I thought it was time to incorporate it)
* All functions should now use the `opts_*` internal API for option arrays.
* As a side result, I've also added some functions to convert to/from option array and plain cell arrays with `{'key=value', 'key', ...}` syntax (i.e. legacy format for options).
* Complexity has been reduced from 97 to 27 as in the overview below:
Function       |Complexity …
=> Another round of refactorings

test/private/testMatlab2tikz.m
See https://github.com/matlab2tikz/matlab2tikz/pull/602 for discussion.
=> improve behavior of testsuite on Windows octave

src/matlab2tikz.m, test/suites/ACID.MATLAB.8.3.md5, test/suites/ACID.MATLAB.8.4.md5, test/suites/ACID.Octave.3.8.0.md5, test/suites/ACID.m
Fixes #601 - stairSeries and areaSeries not toggling off legend entries if not in the legend.
=> Fix stairs and area legend

test/private/execute_hash_stage.m, test/private/testMatlab2tikz.m
* oddly this results in a strong speedup of testsuite execution
* this eases the developers life, since now updated hashes in the file are always noticed
* `clear getReferenceHash` only worked in Matlab
* `clear functions` has unwanted side effects (`getEnvironment` could not be found anymore)
see https://github.com/matlab2tikz/matlab2tikz/commit/05520b8850b0e1a1a9d42f476d8ef5e06a7a04a6#commitcomment-10642865
=> do not store hashTable as persistent

test/private/errorHandler.m
There is no need in interpreting it in any environment, as there
should not be any escape sequences in there anyway.
This fixes #611.
There has been no formal testing, only visual since this happens within an error path and not within normal execution.
=> Error handler should just output message

test/suites/ACID.MATLAB.8.3.md5, test/suites/ACID.MATLAB.8.4.md5, test/suites/ACID.m
By toggling the 'visible` property, the callback gets triggered
and hence we work around bug #638.
This fixes #638.
=> Fix `bodeplots` test (42)

test/suites/ACID.Octave.3.8.0.md5, test/suites/private/herrorbar.m
Fixes `plot failed` for `ACID(74)` on octave (as observed on Travis).
This is an issue in the used `herrorbar.m` [FEX](http://www.mathworks.com/matlabcentral/fileexchange/3963-herrorbar).
Verified visually, updated hash of octave. Matlab is not affected.
=> Fix herrorbar octave

test/suites/ACID.MATLAB.8.3.md5, test/suites/ACID.MATLAB.8.4.md5, test/suites/ACID.Octave.3.8.0.md5, test/suites/ACID.m
ACID(81) now doesn't return `plot error` on octave. Workaround used is to explicitly set the axis limits. Thus hashes of MATLAB were also affected.
=> fix pColorPlot (ACID(81))

src/matlab2tikz.m
This fixes #680 by ignoring, since support for lighting is unlikely to be introduced into `pgfplots`
=> Silently ignore `light` objects

src/matlab2tikz.m
This fixes #693 by just issuing a warning and referring back to the issue where a solution is provided.
I think it is more convenient to refer to the issue than to provide a full explanation, since there we are more at liberty to write a detailed explanation online than in the code.
=> Warn about faceted interp shader

src/matlab2tikz.m, src/private/errorUnknownEnvironment.m, src/private/getEnvironment.m, src/private/isVersionBelow.m, src/private/m2tUpdater.m, src/private/versionArray.m, src/private/versionString.m
This addresses most of #584, i.e. the updater
- is Semantic Versioning-aware, 
- will give a basic interpretation of the upgrade size (i.e. major vs minor vs patch),
- will show the relevant part of the changelog to the user if they it ask for it,
- will perform the upgrade *after* TikZ conversion instead of before.
As a cherry on top, I made the code a bit more modular.
What is in #583, but isn't implemented here is the automatic options or the options to upgrade certain versions automatically. I don't think those are nice-to-haves, but not crucial.
=> Improve updater

AUTHORS.md
This PR is a notice that I will take over the job as maintainer from @nschloe, as both of us discussed briefly during the weekend. With this PR, I also want to show my appreciation for the great work that @nschloe has done for `matlab2tikz` (and I hope, that he will continue to do in the future) :+1: .
Nico has also set the gears in motion to transfer the account on FileExchange to @matlab2tikzBot (or rather, the corresponding [FEX user](http://www.mathworks.com/matlabcentral/profile/authors/6696984-matlab2tikz)), but we are waiting for The MathWorks to carry out this change.
My intention with the @matlab2tikzBot accounts (on GitHub, FEX and GMail), is that we can use it as a shared account amongst developers for e.g. integration with third parties (FEX as the most important one, but also …
=> Maintainer change

test/data/converted/Makefile, test/tex/Makefile
fixes #661 
Tested on tip of `develop` with all other currently pending PRs merged locally. Compiles the output of `testGraphical()` fine, using `make -j4`. Tested with octave.
=> testsuite: change from lualatex to pdflatex

logos/matlab2tikz.svg
This makes sure that other SVG editors show the whole logo, not only a part.
Not high-priority, but it bothered me every time I opened the file.
I don't know how well most SVG editors support font fallbacks, so I didn't have a go at that to also make sure that rendering is better when Liberation Sans is not installed (e.g. Illustrator CS6 dislikes it when not all fonts are installed on your system).
=> Fix page border of logo

src/matlab2tikz.m
fixes #710
Note: TickLabels don't currently support different interpreters in MATLAB.
=> TickLabels - fix escaping

test/saveHashTable.m
This fixes #634. By default, I just ask what action should be performed on tests for which there is a reference hash, but no corresponding test in the status array. The action can be set using the `removedTests` parameter.
I'm not completely satisfied with that name, so suggestions are more than welcome!
This PR can [skip ci] since Travis doesn't cover that part of our code.
=> Save hash table selective

src/matlab2tikz.m, test/suites/ACID.MATLAB.8.4.md5
This is an intermediate fix for `contourf` plots in HG2 where the `X` and `Y` arguments are matrices.
This allows for the whole contour plot to have special figures as discussed in #721.
What doesn't work yet (as indicated by a `FIXME` in the code), is showing the boundary of the contour surface. We now show the bounding box instead. The actual contours, however, seem alright.
You can try with the following MWE
```matlab
N = 20;
[X,Y] = meshgrid([1:N],[1:N]);
subplot(1,3,1);
contourf(X,Y,peaks(N),50,'edgecolor','blue','linestyle','--')
subplot(1,3,2);
contourf(X+Y/2,Y,peaks(N),50,'edgecolor','none')
subplot(1,3,3);
contourf(X+sin(Y),Y-cos(X),peaks(N),50,'edgecolor','red')
matlab2tikz('test.tikz','standalone',true)
!pdflatex test.tikz
open test.pdf
```
=> Contourf matrices

src/matlab2tikz.m
From a first analysis: MATLAB bodeplots consist of groups of two lines (Magnitude, Phase). The lines have no 'DisplayName' but their common parent has one
=> Fixed #700, legends of bodeplots not showing

AUTHORS.md
I added @RPeschke and @dachziegel to contributor list. Both, please complain if you'd rather have just your username in that list instead (or if you have any other request).
=> Add contributors

test/suites/ACID.Octave.3.8.0.md5, test/suites/ACID.m
This fixes the RNG seed in Octave as well. For me, this makes the test reliable, so I marked it as such. Hopefully Travis agrees with me.
This fixes #647 and alleviates #368.
=> Fix seed of RNG in Octave for `texrandom`

src/matlab2tikz.m
Don't throw an error here, to fix #739.
We don't have any test cases that cover this branch anyway.
I really wonder whether that error is really needed. I ran a `git blame`
on this and I tracked along the following commits:
* 1a0e89ee where I just change some whitespace formatting
* 20d9fc8e (whitespace above the error)
* 9fbf9363 where Nico already has a similar error message in place
but the function is used for a generic color conversion (instead of patches).
So my presumption is that the code was changed, the error message carried over
without a full check on whether it was really needed.
Anyway, the current change MAY cause compile errors if I'm being to quick in
removing the error. I expect we will see some bug reports if that's the case,
so I left a comment in the code to help …
=> Allow patchcolor 'none'

src/figure2dot.m, src/matlab2tikz.m, src/private/m2tstrjoin.m, test/private/m2tstrjoin.m
When I was trying to debug some stuff in Octave, I noticed that `figure2dot` doesn't work in Octave. I took the opportunity to clean up the code a bit and add some new features.
This `figure2dot` function allows to translate a HG object into a DOT (GraphViz) file that represents the parent/children relationship and shows some of the relevant properties for each node. This allows to construct figures such as
=> Figure2dot improvements

src/cleanfigure.m
This replaces the complex logic in pruneOutsideBox, that replaced non visible data points.
The new code is much easier to understand and faster due to vectorization.
These do not cause the build to fail.
|   Testcase |                   Name |                       OK |                                                                      Status |
| :--------- | :--------------------- | :----------------------: | :-------------------------------------------------------------------------- |
|  `ACID(1)` |     `multiline_labels` | :heavy_exclamation_mark: | hash 21a208748863224355861184cf9910f7 != (01d4eeae27254d91a0f8316897e23e81) |
|  `ACID(6)` | `sine_with_annotation` | :heavy_exclamation_mark: | hash 995cd2a901446c59f85552d48025ba27 != (7d415c014eec35c249802eb3a3ee519e) |
| `ACID(10)` | …
=> Vectorize pruneOutsideBox

src/cleanfigure.m, test/suites/ACID.Octave.3.8.0.md5
modified:   src/cleanfigure.m
So here is the vectorized version of segmentsIntersect and segmentVisible. Some things to note:
1. The function which mow takes up the main chunk of segmentsIntersect was crossLines. This function is used later on in move to Box. I havent had time to check whether this can be vectorized too.
2. So for my personal use cases (my own figures) This speeds up cleanfigure from about 35s to 7s. However, this doesnt seem to be the case for the testcase with with a simple sinus. I cant really tell why.
3. I only have R2015 so some additional tests fail due to that, here the output from travis:
These do not cause the build to fail.
|   Testcase |                   Name |                       OK | …
=> Vectorize segmentsIntersect and segmentVisible functions.

test/compareTimings.m, test/private/execute_tikz_stage.m
This is my processing script (see #737) for timing the test cases.
This is only the processing, you need to run the test suite yourself (repeatedly, if you want more reliable results).
I haven't fully checked whether there is a burn-in period of the timing results, since each the easies way to get the results, is to run the test suite repeatedly. So possibly, the caches get wiped by the time a test case is run again. If that's the case and a problem, we need to tweak the test framework a bit.
The output looks like this for #737 (after) vs. this branch (before):
=> Timing the test suite

src/figure2dot.m, src/matlab2tikz.m, src/private/guitypes.m
This removes the only FIXME from `figure2dot`.
Note: only executed mentally, so wait for Jenkins and Travis to be sure.
=> Extract function `guitypes`

.travis.yml, matlab2tikz.sublime-project, runtests.sh
It bothered me that the Jenkins script and Travis script are a bit different, while there should be need for this.
Also: in Jenkins I had quite a few commands (see here) in the runner, this can now be tracked in git.
Currently, in Jenkins I have the following script:
```bash
if [ -f ./runtests.sh ]; then
./runtests.sh ${Runner% *}
else
echo !! Running compatibility script !!
export CONTINUOUS_INTEGRATION=true
cd test
$Runner "runMatlab2TikzTests()"
fi
```
to facilitate PRs while this one is not merged in.
Afterwards, that should simplify to just `./runtests.sh $Runner` (and some tweaking of the Build Matrix).
=> Test script

src/cleanfigure.m
This is a clean version of #761 
@okomarov  simplifyLine does operate on a different set of data points than pruneOutsideBox or movePointsCloser. The former acts on isInBox and the latter two on ~isInBox. Therefore they should be easily replacable
=> Move simplifyLine after pruneOutsideBox and movePointsCloser.

test/saveHashTable.m
This is a follow-up on #720 to address the comments of @okomarov.
We really need this in, since `saveHashtable` in Octave was broken (I only tested the previous PR with MATLAB, my bad!).
=> Octave hashtable

src/cleanfigure.m, test/suites/ACID.Octave.3.8.0.md5
So when I was writing the 3D projection part in #779, I realized, that I had to do a lot of restructuring. 
To keep it "cleaner" I decided to pull it out and make a new PR. So there are some new functions:
```matlab
[xData, yData] = getVisualData(meta, handle)
[xLim, yLim] = getVisualLimits(meta)
replaceData(handle, id_replace, dataReplace)
insertData(handle, id_insert, dataInsert)
removeData(meta, handle, id_remove)
removeNaNs(meta, handle)
```
I believe their names are rather self explanatory. To get them working i had to restructure our simplification functions slightly. In the end I decided, that every function should generate lists of indices e.g. id_replace for all the data that should be replaced and removed and so on.
This unifies the data handling and should help us to maintain …
=> Cleanfigure restructure

src/matlab2tikz.m, test/suites/ACID.MATLAB.8.4.md5
Now draws baseline in barplots and stemseries plots:
ACID(32)
=> drawBaseline for barplots and stemseries

src/cleanfigure.m, test/suites/ACID.Octave.3.8.0.md5
This fixes an awkward bug in simplifyLine that I actually thought I had fixed o.O.
In the end the accounting for the elements of the previous line segments was bogus and completely overcomplicated.
=> Fixed incorrect accounting for previous line segments in simplifyLine

src/matlab2tikz.m
Fixes #383 (x tick labels ignored when datetime) and b2ff705 removes #802 conversions of graphic handles.
=> Handle datetime ticks automatically

src/matlab2tikz.m, test/suites/ACID.MATLAB.8.3.md5, test/suites/ACID.MATLAB.8.4.md5, test/suites/ACID.Octave.3.8.0.md5, test/suites/ACID.m
When a line has deviations, it is always visible.
This should fix #812.
=> Also check deviations for plot visibility & drawLine refactoring

src/cleanfigure.m
Hi,
as the title says, this puts text removal into its own subfunction, considerably cleaning up revursiveCleanup.
While we are at it, removed the intent parameter from recursiveCleanup, that might have some historic origin. Additionally, the early return for quiverplots seems to be nonfunctional. Remove it was well.
=> Put text removal into own function and prepare deprecation

src/cleanfigure.m, test/suites/ACID.MATLAB.8.3.md5, test/suites/ACID.MATLAB.8.4.md5, test/suites/ACID.Octave.3.8.0.md5
Currently pixelate is kind of buggy.
The reason is, that it assumes an explicit order in both dimensions, hidden in the diff(...). Instead use the matlab build in function unique, that finds us the unique pixels without any hassle.
P.S: It is not 100% mathematically correct, as there is the theoretical possibility, that the first and last pixel is duplicated *shrug*.
=> Rework pixelate

src/cleanfigure.m, src/matlab2tikz.m, test/private/execute_tikz_stage.m
In #820, I noticed that the `interpretTickLabelsAsTex` parameter is no longer used anywhere within the code.
However, for R2014a and older, it still makes sense to use it.
In this PR, I have reintroduced the parameter via the default value (which is used in HG1). In HG2, nothing changes and the parameter is ineffective, hence, the warning procedure.
I also took a bit of time to clean up some bits of code in the vicinity: those should be functionally identical.
=> Tick label interpreter + cleanup

.travis.yml
Travis has [migrated](https://blog.travis-ci.com/2015-11-27-moving-to-a-more-elastic-future) from OpenVZ to GCE, so apparently, `gdb` is no longer available.
This PR is to fix this on our end, if we can (this time against `develop` instead of `master`).
=> Travis GCE migration

src/matlab2tikz.m
The autolabel option of matlab2tikz is working fine, but if you change your plots, because e.g. you plot an additional line, all labels change.
Therefore, it is convenient to add the label you want to have in tex to the Tag property of your line in matlab. When exporting with autolabels, the original labels are reproduced for compatibility and additionally the Tag will show up as a label.
=> add labels to plot according to Tag property of line

src/matlab2tikz.m, test/suites/ACID.MATLAB.8.3.md5, test/suites/ACID.MATLAB.8.4.md5
So i looked into bar plots due to the issues we have with them. I found, that a lot of the draw options handling can be generalized for different plots, e.g. histogram/barplots/areas
So i did that and cleaned up various other occurrences of opt_print while i was at it.
I did not bother to check all the differences yet, as i would like to know whether there is interest at all int that PR
=> Cleanup of draw options gathering

src/matlab2tikz.m
We had a function that generated lineOptions, but strangely put the getters for those options outside the function, passing them as arguments. 
Clean that up and use the getLineOptions whenever possible. Also utilize the isLineVisible function, when LineStyle and LineWidth are only used to check for visibility.
I have kept the generally used output [m2t, Options] however i am unsure if we shouldnt reduce it to just Options when m2t is not changed
=> Cleanup gathering of lineoptions

src/cleanfigure.m, test/suites/ACID.MATLAB.8.3.md5, test/suites/ACID.MATLAB.8.4.md5, test/suites/ACID.Octave.3.8.0.md5, test/suites/ACID.m
Previously we didn't check whether it was a line or not #788. This might have the undesired behaviour, that markers outside of the visible box would not be removed.
By checking for lineplots, we can resolve this. Additionally, as markers are only plotted inside the box, we can simplify the code a bit.
This also adds a test that checks the behaviour.
=> Check for lines in pruneOutsidebox

src/matlab2tikz.m
As @okomarov has mentioned in #848, the naming of the variables is missleading. Clarify that.
=> Renamed output of addPlotyyReference to clarify their content

src/matlab2tikz.m
As the title says, it is not defined in getPatchShape. See #852 
To preserve encapsulation, get it from patchOptsion
=> Fix missing definition of isFaceColorFlat

src/figure2dot.m
@okomarov What you wanted, I hope :smile: 
This shows the related Axes for legend objects.
Confirmed working in both HG1 and HG2 (don't know about Octave).
E.g. for 
```matlab
hold all
plot(1:10)
plot(2:11)
plot(3:12)
legend('a','b')
```
this produces the following DOT figure in HG2 (HG1 also shows the property, but the overall data structure is more complicated). The green highlight is what this PR adds:
=> figure2dot: also show "Axes" property

src/matlab2tikz.m
We should exit prettyPrint early if perseStrings is set to false. However, sometimes the string is given as a char array, which we have to turn into a cell containing the string. This is done with cellstr().
This should fix #86
=> Fix prettyPrint with parseStrings=false

src/matlab2tikz.m
As discussed in #896 the code currently always draws the edge. This was currently shadowed if the edge color was the same as that of the patch and/or if it was set explicitely.
Therefore, add a check for the visibility of a line of patch plots so the edge is only drawn when visible.
=> Check for edge visibility of patches

src/matlab2tikz.m, test/suites/ACID.MATLAB.8.3.md5, test/suites/ACID.MATLAB.8.4.md5, test/suites/ACID.Octave.3.8.0.md5
Hi,
this is a try on #785 and hopefully later also #845 and #840 . 
Currently barplots are stacked on top of each other. This can be avoided by removing the "bar shift" argument and adding "xbar/ybar" to the axis environement, as following the pgfplots manual this calculates the shifts automatically.
```latex
/pgfplots/xbar={<shift for multiple plots>} (style, default 2pt)
This style sets /tikz/xbar and some commonly used options concerning horizontal bars 
for the complete axis. This is automatically done if you provide xbar as argument to an 
axis argument, see above. The xbar style defines shifts if multiple plots are placed 
into one axis. It draws bars adjacent to each other, separated by
<shift for multiple plots>. Furthermore, it sets the style bar cycle list and sets tick and …
```
=> Fix barplots

src/matlab2tikz.m
This is related to #899 
Similarly to the variable size case, respect the edge color of markers. I dont really know if we couldnt simplify this further.
=> Always respect EdgeColor in Scatterplots

src/matlab2tikz.m
Move the addition of bar shift auto to the setBarLayoutOfBarSeries function and only apply it to grouped plots. This fixes #901.
=> Fix incorrect bar shift auto assignment for stacked barseries

src/cleanfigure.m
this is a very hacky try to make datetick compilable for m2t inspired by #905.
The idea is simple. Tacke the rather stupid matlab format and project it into a reasonable range tixz can work with. There is obviously a big drawback, as it is done for all the the axes.
If the xaxis is in datetick one does
```matlab
cleanfigure('transformDates', 'x')
```
=> Normalize axis data

src/matlab2tikz.m
MATLAB warns that `mkdir('')` may stop working in the future.
As such, only do the `mkdir` part when an actual directory is provided.
This PR makes sure that this warning no longer occurs.
=> Only mkdir when directory name is specified

src/matlab2tikz.m
Currently ticklabels were cells of a single cell containing a string. This could break the code as sprintf doesnt take a cell. As a workarround  transform it into cells of string as we do for log scaled plots.
This should fix #926.
=> Transform semantic ticklabels into a cell of strings

src/matlab2tikz.m, test/suites/ACID.MATLAB.8.4.md5, test/suites/ACID.m
Hi,
I might have found a solution for manual positioning of colorbars with new Matlab versions, see issue #933.
The (undocumented) `Axes` property of a colobar provides a handle for it's associated axes. Comparing the axes' and the colorbar's posititions along with the `AxisLocation` property, we can decide wheather to use the colorbar template "left" or "right".
The following example works for me:
```
ax = subplot(221);
cb = colorbar('Position',[ax.Position(1)+0.3*ax.Position(3),ax.Position(2),0.02,0.2],...
'AxisLocation','in');
ax = subplot(222);
cb = colorbar('Position',[ax.Position(1)+0.7*ax.Position(3),ax.Position(2),0.02,0.2],...
'AxisLocation','in');
ax = subplot(223);
cb = colorbar('Position',[ax.Position(1)+0.3*ax.Position(3),ax.Position(2),0.02,0.2],...
'AxisLocation','out');
ax …
```
=> Manual colorbar location

AUTHORS.md
This was los within my personal branches. Originally, those were intended for the previous release, but here they are now.
No code is affected, so CI does not need to be trusted.
=> Add authors

src/matlab2tikz.m
Line style none gets ignored and `shader=interp faceted` is picked, resulting in **wrong image** and very **heavy .pdfs**.
```
h = ribbon(randn(3,1));
set(h,'CData', get(h,'ZData'),'FaceColor','interp','LineStyle','none')
view(0,90)
```
For this example, the size of the pdf is negligible. On other figures, I get figures > 1MB while with the correct `shader=interp` they are reduced to about 100KB, so an **order of magnitude** better!
=> Fix choice of shader for surface

src/matlab2tikz.m
Improves handling of Error Bars: it sets 'error bar style' and 'error mark options' appropriately. Solves #960.
Test summary:
In my setup (Matlab 2016b in macOS Sierra) the **untouched**, current (develop da9a24e) version failed in 19 tests:
```
suite = @ACID;
alltests = [1:105];
reliable = [2:5 7:9 11:17 19:23 25:33 35:37 39 41 44:47 50:57 59:77 79:93 95:96 98:105];
unreliable = [1 6 10 18 24 34 38 40 42:43 48:49 58 78 94 97];
failReliable = [8:9 12 20 23 36 45 55:57 61:62 68 70 81:82 95:96 101];
passUnreliable = [34 38 40 49 94 97];
skipped = [17];
```
|            | Pass | Fail | Skip | Total |
| :--------- | ---: | ---: | ---: | ----: |
| Unreliable |    6 |   10 |    0 |    16 |
|   Reliable |   69 |   19 |    1 |    89 |
|      Total |   75 |   29 |    1 |   105 |
```
Build fails …
```
=> Improve handling of errorbars

src/private/m2tUpdater.m
This only works in MATLAB, but brings the github issues
within reach of our users.
Re-PR of #957, against develop this time. CI is worthless in this case, since the updater is not covered anyhow.
=> Github issue numbers -> URL in updater changelog

src/matlab2tikz.m
In R2016b datetime ticks are used directly rather than in just rendering the ticks labels. Convert `datetime` ticks to `datenum`. 
The test for versions below R2016b has still to go through the undocumented property, hence the try catch remains. 
Fixes #963
=> Fix #963, i.e. datetime ticks in R2016b 

src/matlab2tikz.m
Fixes #954.
Replace `'draw=none'` with `'only marks'`. when we have markers.
=> Only marks for legend consistency

src/matlab2tikz.m
Avoid processing drawImage for empty data.
=> Only export an image if it is not empty. This fixes #999

src/matlab2tikz.m
Hello!
In MATLAB R2016b the LegendPeerHandle appdata field was renamed to
LayoutPeers (I think it is undocumented, the info comes from the docs
of this third party toolbox: ttp://rosa.unipr.it/FSDA/release_notes.html).
I added a version check to ensure that the correct field name is used on
recent MATLAB versions.
=> Fix a bug in isAxisMain()

src/matlab2tikz.m
Using matlab2tikz in GNU/Octave 4.4.1 would not produce legends in the tikz code.
=> Fix for GNU/Octave not including legends

src/matlab2tikz.m
I.e. replace errors on unknown objects with warnings.
This helps with newer additions to the HG(2) object types: instead of failing
altogether, m2t now translates whatever it recognizes and warns about the rest.
Also, by calling `drawNothing`, through the `handleObject` wrapper, this allows a user
to attach a custom handler via `m2tcustom` to specific objects.
=> For unknown objects -> call `drawNothing`

src/matlab2tikz.m
Added support for "arrowshape" and "doubleendarrowshape" type objects in handleAllChildren fcn
=> Fix arrow and doublearrow annotation not being drawn in final output

src/matlab2tikz.m
An images `AlphaData` channel might be of type `logical`, but `imwrite` expects alpha to be of type `double, uint8, uint16`. This converts the alpha channel data to double.
=> Fix setting alpha data in PNGs

src/matlab2tikz.m
This is an updated version of https://github.com/matlab2tikz/matlab2tikz/pull/1060.
Consider the following Matlab and Tex files:
```Matlab
valign = {'base', 'bottom', 'middle', 'cap', 'top'};
halign = {'left', 'center', 'right'};
figure;
hold on;
ylim([0, 4]);
xlim([0, 6]);
for jj = 1:length(valign)
for kk = 1:length(halign)
plot(jj, kk, 'x', 'MarkerSize', 10, 'Linewidth', 2);
text(jj, kk, 'Matlab', 'HorizontalAlignment', halign{kk}, 'VerticalAlignment', valign{jj});
end
end
set(gca, 'XTick', 1:length(valign));
set(gca, 'XTickLabels', valign);
xlabel('Vertical Alignment');
set(gca, 'YTick', 1:length(halign));
set(gca, 'YTickLabels', halign);
ylabel('Horizontal alignment');
box on;
matlab2tikz('textPosition.tikz');
```
```Latex
\documentclass[]{standalone}
\usepackage{pgfplots} …
```
=> Fix text positioning
