matlab2tikz/matlab2tikz

test/suites/ACID.m

* be warned: generation of PDF from MATLAB is incorrect (green background missing)
* m2t output will be fixed by PR #510
* tested on R2014a and R2014b
* testcase for issue #6

add testcase overlappingPlots = ACID(98)

---

test/suites/ACID.m

thank you @okomarov
fixes PR #512

fix ACID test: do not create new figure

---

test/suites/ACID.m

Output as shown in https://github.com/matlab2tikz/matlab2tikz/pull/526
ACID(99)
Tested in R2014b and test is only for this product.

extend testcase to cover horizontal orientation

---

src/matlab2tikz.m

Reverts matlab2tikz/matlab2tikz#523

Revert "3D axis detected from view"

---

src/matlab2tikz.m

Refer to #523 + fix for Octave avoiding `handle()` in `getPositionOfText`

is3D with fix fopr Octave handle()

---

src/cleanfigure.m
test/suites/ACID.m

* implement handling of 3D case
* improve 2D handling
* extend testcases
* fixes issue #378 
Tested on R2014a/b and octave 3.8.2.

fix issue #378 of removed textboxes

---

src/cleanfigure.m
test/suites/ACID.m

* fixes issue #226
* adds ACID test `@pruneOutsideBox`
* checked on R2014b and octave

fix extend pruneOutsideBox for stairs() plot

---

test/private/testMatlab2tikz.m
test/runMatlab2TikzTests.m

Ensure that paging is disabled when running travis

---

src/matlab2tikz.m

This partly addresses #391. So no new features here, mostly refactorings, although I did some tiny changes here and there (see commit messages in those cases).
Statistics:
Function          |Complexity 
----------------------------|-----------
`drawPatch`         |    22     
`matlabTicks2pgfplotsTicks` |    19     
`drawScatterPlot`      |    18     
`getColorbarOptions`    |    15     
`shaderOptsSurfPatch`    |    14     
`getMarkerOptions`     |    13     
`drawContour`        |    13     
`drawBarseries`       |    12     
`findLegendInformation`   |    11     
**Total**          |    137  
Each commit has been tested with R2014b. The whole changeset (i.e. everything until f31dd72) has been tested with R2014a as well. For the Octave part, I rely on Travis.

Simplification

---

src/matlab2tikz.m

Try to speed up make table by avoiding cellfun

Make table3

---

src/matlab2tikz.m
test/suites/ACID.MATLAB.8.3.md5
test/suites/ACID.MATLAB.8.4.md5
test/suites/ACID.Octave.3.8.0.md5
test/suites/ACID.m

Let's see how I have to update the hashes...

FIX #587 -- pipe character and interpreter tex

---

src/matlab2tikz.m
test/suites/ACID.MATLAB.8.3.md5
test/suites/ACID.MATLAB.8.4.md5
test/suites/ACID.Octave.3.8.0.md5
test/suites/ACID.m

Fix issue #581.
Adapt test-case to use a non-quadratic image.

Fix #581 imagesAsPng()

---

src/matlab2tikz.m
test/suites/ACID.m

see https://github.com/matlab2tikz/matlab2tikz/pull/604/files#r28495108

add FIXME notes and comments

---

src/matlab2tikz.m

The last set of simplifications to fix #391.
Covered by the R2014b headless tests to make sure everything still works.
I also added a link to the FIXME regarding RGB scatter plots to a stackoverflow post by Christian for a way to work around that hiatus in pgfplots and our code.

Last round of refactorings!

---

src/matlab2tikz.m

Require pgfplots 1.12 for `z buffer=sort`

---

src/matlab2tikz.m
test/suites/ACID.m

Fix quiver

---

CONTRIBUTING.md
test/README.md

I made a first attempt at writing a `CONTRIBUTING.md` file, so this PR will close #599 when merged.
In the process, I also updated the `test/README.md` to which I referred.
Over time, we might want to put more of the wiki into that document, but for now, I think this is fine.
All comments are more than welcome.

Contributing.md

---

src/matlab2tikz.m
test/suites/ACID.MATLAB.8.3.md5
test/suites/ACID.MATLAB.8.4.md5
test/suites/ACID.Octave.3.8.0.md5
test/suites/ACID.m

This fixes #682 , but I'm currently running the test suite to check regressions.
**edit:** Test suite passes in all environments on Mac.

Fix #682: patch with no edge color

---

src/matlab2tikz.m

`set(0, 'ShowHiddenhandles', 'on')` sets global state.
Instead, the same effect can be gotten with using:
- `findall` instead of `findobj`
- `allchild(h)` instead of `get(h, 'Children')`
I know I have raised the topic before, but I can't remember in which issue report. In any case, this PR removes buggy behavior related to the `ShowHiddenHandles` property and how we handled it before:
- when `m2t` crashes, that property would be left in the `'on'` state
- when `m2t` finishes with success, that property would be set to the `'off'` state, regardless of what its state was before `m2t` started running.
Using `onCleanup` could get very similar results as this PR (in fact, that's how the `allchild` function is implemented in MATLAB). But I think the current approach is a lot cleaner.
In the …

Use findall and allchild instead of global settings

---

AUTHORS.md
src/matlab2tikz.m

This fixes #713. I also took the opportunity to refactor a bit and fix a typo.
This has been tested on R2014a, R2014b on Mac without a hickup.

Fix image dimensions swapped

---

src/matlab2tikz.m

bugfix for #728

---

test/makeTravisReport.m

Requested by @okomarov, I kept a bit of the verbosity, but I'm not feeling strongly in favor/against one thing or another.

Make new/expected hash clearer in reportt

---

src/matlab2tikz.m

This is a rebased version of #716 to allow further testing.

Pr716 rebased

---

test/README.md

[skip ci] only documentation changed

Mention Jenkins in test/README.md

---

src/cleanfigure.m
test/suites/ACID.Octave.3.8.0.md5

This is a rebased version of PR #750, that avoids a conflict with the Octave hash table.

Vectorize move points closer rebased

---

runtests.sh

This should fix the test runner problems noticed by @okomarov in #765

runtests exit on error

---

test/private/calculateMD5Hash.m

Speedup hash generation

---

.gitignore

This should prevent https://github.com/matlab2tikz/matlab2tikz/pull/791#issuecomment-153369312 
from happening again.

Ignore autosave files and Octave workspaces

---

src/cleanfigure.m
test/suites/ACID.MATLAB.8.3.md5
test/suites/ACID.MATLAB.8.4.md5
test/suites/ACID.Octave.3.8.0.md5
test/suites/ACID.m

This fixes an embarassing bug, where only the last line segment would be simplified.
Damn, i am feeling really bad, that i screwed it up. Luckily it bit me, when i handled my large data sets

Fix broken lineSimplify

---

src/matlab2tikz.m

Just some minor cleanup:
- removed an unused function
- fixed spacing in a function (it seems our automatic whitespace tool is a bit too coarse at the moment), I will have a look whether we can't make `git` do some things in a pre-commit hook to avoid at least trailing whitespace.

Minor cleanup

---

src/matlab2tikz.m

allows to use rotated tick labels

Tick label rotation

---

src/cleanfigure.m

Grml,
another small thing i noticed, with my own plots. When we have a mixed linestyle aka '-o' then pixelation will create new lines as it doesnt check for the line segments.
I have to add Test for that

Fix pixelation to only happen when treating Markers.

---

src/matlab2tikz.m

So this one poped up, when i already had set the cleanup as ready.
Was easier than expected and simplifies the function tremendously

Simplify splitLine

---

src/cleanfigure.m
test/suites/ACID.MATLAB.8.3.md5
test/suites/ACID.MATLAB.8.4.md5
test/suites/ACID.Octave.3.8.0.md5
test/suites/ACID.m

This is the simplification function proposed in #863.
I have also modified ACID(28) to add a use case for this simplification algorithm.

Added a simplification algorithm for stair plots

---

src/matlab2tikz.m

Create output directory before fopen

---

test/suites/ACID.m

Fixes error from invalid legend syntax

Fixes invalid syntax in R2016b

---

src/matlab2tikz.m

I extended the drawArrow()-function by the DoubleEndArrows

extended drawArrow() for DoubleEndArrow

---

src/matlab2tikz.m

Fixes #582 
Properly handles colored backdrop of the contours.

Fix colour of the backdrop and handle same level 'holes'

---

src/matlab2tikz.m

Add forget plot in case not all Scatters are in the legend

Add forget plot to Scatter plot

---

src/matlab2tikz.m

Axis location 

---

src/matlab2tikz.m

https://github.com/matlab2tikz/matlab2tikz/issues/1023

Issue #1023 Plot3 'markerEdgeColor'

---

src/matlab2tikz.m

Fix #1006: create legend introduced in R20177b+

---

src/matlab2tikz.m

Hi,
Thanks for creating this tool / script. I felt like this small documentation was missing as I've managed to only guess this is how this will work.
Regards.
Also, another question:
Why are you using `MATLAB2TIKZ()` (uppercase)? The function must be called in lower case for Octave users for as far as I can see...

Explain a bit better the options' combinations
